package web.entity;
// Generated 2017/9/8 上午 11:40:03 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * Json generated by hbm2java
 */
public class Json  implements java.io.Serializable {


     private Integer id;
     private Serializable data;
     private Date time;

    public Json() {
    }

    public Json(Serializable data, Date time) {
       this.data = data;
       this.time = time;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Serializable getData() {
        return this.data;
    }
    
    public void setData(Serializable data) {
        this.data = data;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


