package web.entity;
// Generated 2017/9/8 上午 11:40:03 by Hibernate Tools 4.3.1



/**
 * Table generated by hbm2java
 */
public class Table  implements java.io.Serializable {


     private Integer id;
     private String test;

    public Table() {
    }

    public Table(String test) {
       this.test = test;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTest() {
        return this.test;
    }
    
    public void setTest(String test) {
        this.test = test;
    }




}


